import jsPDF from 'jspdf'
import type { PassportFormData } from '@/components/PassportForm'
import type { GNFormData } from '@/components/GNForm'
import type { BusinessFormData } from '@/components/BusinessForm'
import type { BirthCertificateFormData } from '@/components/BirthCertificateForm'
import type { DrivingLicenseFormData } from '@/components/DrivingLicenseForm'
import type { PoliceClearanceFormData } from '@/components/PoliceClearanceForm'
import type { NICRenewalFormData } from '@/components/NICRenewalForm'

const PLACEHOLDER = '________________________'

function drawField(
  doc: jsPDF,
  label: string,
  value: string | undefined,
  yPos: number,
  valueX = 70,
): number {
  const pageWidth = doc.internal.pageSize.getWidth()
  const valueMaxWidth = pageWidth - valueX - 20

  doc.setFont('helvetica', 'bold')
  doc.text(`${label}:`, 20, yPos)

  doc.setFont('helvetica', 'normal')
  const display = value?.trim() ? value.trim() : PLACEHOLDER
  const lines = doc.splitTextToSize(display, valueMaxWidth)
  doc.text(lines, valueX, yPos)

  return yPos + 12 * Math.max(1, lines.length)
}

function drawSignatureFooter(doc: jsPDF, yPos: number) {
  doc.setLineWidth(0.2)
  doc.line(20, yPos, 80, yPos)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'italic')
  doc.text("Applicant's Signature", 30, yPos + 5)
  doc.text('Generated by Rathna AI Assistant', 105, 280, { align: 'center' })
}

function printPdfDoc(doc: jsPDF) {
  const blob = doc.output('blob')
  const url = URL.createObjectURL(blob)

  const iframe = document.createElement('iframe')
  iframe.style.position = 'fixed'
  iframe.style.right = '0'
  iframe.style.bottom = '0'
  iframe.style.width = '0'
  iframe.style.height = '0'
  iframe.style.border = 'none'
  iframe.src = url

  const cleanup = () => {
    URL.revokeObjectURL(url)
    iframe.remove()
  }

  iframe.onload = () => {
    try {
      iframe.contentWindow?.focus()
      iframe.contentWindow?.print()
    } finally {
      window.setTimeout(cleanup, 1000)
    }
  }

  document.body.appendChild(iframe)
}

function buildPassportPDFDoc(data: PassportFormData) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  })

  doc.setTextColor(0, 0, 0)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('SRI LANKA DEPARTMENT OF IMMIGRATION & EMIGRATION', 105, 20, {
    align: 'center',
  })

  doc.setFontSize(16)
  doc.text('PASSPORT APPLICATION (FORM K)', 105, 30, { align: 'center' })
  doc.setLineWidth(0.5)
  doc.line(20, 35, 190, 35)

  doc.setFontSize(11)
  let yPos = 50

  yPos = drawField(doc, 'Surname', data.surname, yPos)
  yPos = drawField(doc, 'Other Names', data.otherNames, yPos)
  yPos = drawField(doc, 'NIC Number', data.nationalId, yPos)
  yPos = drawField(doc, 'Date of Birth', data.dateOfBirth, yPos)
  yPos = drawField(doc, 'Place of Birth', data.placeOfBirth, yPos)
  yPos = drawField(doc, 'Gender', data.gender, yPos)

  yPos += 5
  yPos = drawField(doc, 'Permanent Address', data.address, yPos)
  yPos = drawField(doc, 'District', data.district, yPos)
  yPos = drawField(doc, 'Phone Number', data.phone, yPos)
  yPos = drawField(doc, 'Service Type', data.serviceType, yPos)

  drawSignatureFooter(doc, yPos + 30)
  return doc
}

function buildGnPDFDoc(data: GNFormData) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  })

  doc.setTextColor(0, 0, 0)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('SRI LANKA GRAMA NILADHARI DIVISION', 105, 20, { align: 'center' })

  doc.setFontSize(16)
  doc.text('GRAMA NILADHARI CERTIFICATE APPLICATION', 105, 30, {
    align: 'center',
  })
  doc.setLineWidth(0.5)
  doc.line(20, 35, 190, 35)

  doc.setFontSize(11)
  let yPos = 50

  yPos = drawField(doc, 'Full Name', data.fullName, yPos)
  yPos = drawField(doc, 'NIC Number', data.nationalId, yPos)
  yPos = drawField(doc, 'Address', data.address, yPos)
  yPos = drawField(doc, 'Reason for Certificate', data.reason, yPos)
  yPos = drawField(doc, 'District', data.district, yPos)

  drawSignatureFooter(doc, yPos + 30)
  return doc
}

function buildBusinessPDFDoc(data: BusinessFormData) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  })

  doc.setTextColor(0, 0, 0)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('SRI LANKA BUSINESS REGISTRATION', 105, 20, { align: 'center' })

  doc.setFontSize(16)
  doc.text('BUSINESS REGISTRATION APPLICATION', 105, 30, { align: 'center' })
  doc.setLineWidth(0.5)
  doc.line(20, 35, 190, 35)

  doc.setFontSize(11)
  let yPos = 50

  yPos = drawField(doc, 'Business Name', data.businessName, yPos)
  yPos = drawField(doc, 'Owner Name', data.ownerName, yPos)
  yPos = drawField(doc, 'NIC Number', data.nationalId, yPos)
  yPos = drawField(doc, 'Business Address', data.businessAddress, yPos)
  yPos = drawField(doc, 'Business Type', data.businessType, yPos)
  yPos = drawField(doc, 'District', data.district, yPos)

  drawSignatureFooter(doc, yPos + 30)
  return doc
}

function passportFileId(data: PassportFormData) {
  return (
    data.nationalId?.replace(/[^\w]/g, '') ||
    data.surname?.replace(/\s+/g, '_') ||
    'Draft'
  )
}

function gnFileId(data: GNFormData) {
  return data.nationalId?.replace(/[^\w]/g, '') || 'Draft'
}

function businessFileId(data: BusinessFormData) {
  return (
    data.nationalId?.replace(/[^\w]/g, '') ||
    data.businessName?.replace(/\s+/g, '_') ||
    'Draft'
  )
}

export function generatePassportPDF(data: PassportFormData) {
  buildPassportPDFDoc(data).save(
    `Passport_Application_${passportFileId(data)}.pdf`,
  )
}

export function printPassportPDF(data: PassportFormData) {
  printPdfDoc(buildPassportPDFDoc(data))
}

export function generateGnPDF(data: GNFormData) {
  buildGnPDFDoc(data).save(`GN_Certificate_${gnFileId(data)}.pdf`)
}

export function printGnPDF(data: GNFormData) {
  printPdfDoc(buildGnPDFDoc(data))
}

export function generateBusinessPDF(data: BusinessFormData) {
  buildBusinessPDFDoc(data).save(
    `Business_Registration_${businessFileId(data)}.pdf`,
  )
}

export function printBusinessPDF(data: BusinessFormData) {
  printPdfDoc(buildBusinessPDFDoc(data))
}

function buildBirthCertificatePDFDoc(data: BirthCertificateFormData) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  })

  doc.setTextColor(0, 0, 0)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('SRI LANKA BIRTH CERTIFICATE DIVISION', 105, 20, {
    align: 'center',
  })

  doc.setFontSize(16)
  doc.text('BIRTH CERTIFICATE REQUEST FORM', 105, 30, { align: 'center' })
  doc.setLineWidth(0.5)
  doc.line(20, 35, 190, 35)

  doc.setFontSize(11)
  let yPos = 50

  yPos = drawField(doc, 'Full Name', data.fullName, yPos)
  yPos = drawField(doc, 'Date of Birth', data.dateOfBirth, yPos)
  yPos = drawField(doc, 'Place of Birth', data.placeOfBirth, yPos)
  yPos = drawField(doc, "Mother's Name", data.motherName, yPos)
  yPos = drawField(doc, "Father's Name", data.fatherName, yPos)
  yPos = drawField(doc, 'NIC Number', data.nationalId, yPos)
  yPos = drawField(doc, 'District', data.district, yPos)

  drawSignatureFooter(doc, yPos + 30)
  return doc
}

function buildDrivingLicensePDFDoc(data: DrivingLicenseFormData) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  })

  doc.setTextColor(0, 0, 0)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('SRI LANKA DEPARTMENT OF MOTOR TRAFFIC', 105, 20, {
    align: 'center',
  })

  doc.setFontSize(16)
  doc.text('DRIVING LICENSE APPLICATION', 105, 30, { align: 'center' })
  doc.setLineWidth(0.5)
  doc.line(20, 35, 190, 35)

  doc.setFontSize(11)
  let yPos = 50

  yPos = drawField(doc, 'Full Name', data.fullName, yPos)
  yPos = drawField(doc, 'NIC Number', data.nationalId, yPos)
  yPos = drawField(doc, 'Address', data.address, yPos)
  yPos = drawField(doc, 'Blood Group', data.bloodGroup, yPos)
  yPos = drawField(doc, 'Vehicle Category', data.vehicleCategory, yPos)
  yPos = drawField(doc, 'License Type', data.licenseType, yPos)
  yPos = drawField(doc, 'Phone Number', data.phone, yPos)

  drawSignatureFooter(doc, yPos + 30)
  return doc
}

function buildPoliceClearancePDFDoc(data: PoliceClearanceFormData) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  })

  doc.setTextColor(0, 0, 0)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('SRI LANKA POLICE DEPARTMENT', 105, 20, { align: 'center' })

  doc.setFontSize(16)
  doc.text('POLICE CLEARANCE CERTIFICATE APPLICATION', 105, 30, {
    align: 'center',
  })
  doc.setLineWidth(0.5)
  doc.line(20, 35, 190, 35)

  doc.setFontSize(11)
  let yPos = 50

  yPos = drawField(doc, 'Full Name', data.fullName, yPos)
  yPos = drawField(doc, 'NIC Number', data.nationalId, yPos)
  yPos = drawField(doc, 'Passport Number', data.passportNumber, yPos)
  yPos = drawField(doc, 'Address', data.address, yPos)
  yPos = drawField(doc, 'Country Applying For', data.countryApplyingFor, yPos)
  yPos = drawField(doc, 'Reason', data.reason, yPos)
  yPos = drawField(doc, 'Phone Number', data.phone, yPos)

  drawSignatureFooter(doc, yPos + 30)
  return doc
}

function buildNICRenewalPDFDoc(data: NICRenewalFormData) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  })

  doc.setTextColor(0, 0, 0)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('SRI LANKA REGISTRATION OF PERSONS DEPARTMENT', 105, 20, {
    align: 'center',
  })

  doc.setFontSize(16)
  doc.text('NATIONAL IDENTITY CARD RENEWAL APPLICATION', 105, 30, {
    align: 'center',
  })
  doc.setLineWidth(0.5)
  doc.line(20, 35, 190, 35)

  doc.setFontSize(11)
  let yPos = 50

  yPos = drawField(doc, 'Full Name', data.fullName, yPos)
  yPos = drawField(doc, 'NIC Number', data.nationalId, yPos)
  yPos = drawField(doc, 'Date of Birth', data.dateOfBirth, yPos)
  yPos = drawField(doc, 'Address', data.address, yPos)
  yPos = drawField(doc, 'Phone Number', data.phone, yPos)
  yPos = drawField(doc, 'Reason for Renewal', data.reasonForRenewal, yPos)
  yPos = drawField(doc, 'District', data.district, yPos)

  drawSignatureFooter(doc, yPos + 30)
  return doc
}

function nicFileId(data: { nationalId?: string; fullName?: string }) {
  return (
    data.nationalId?.replace(/[^\w]/g, '') ||
    data.fullName?.replace(/\s+/g, '_') ||
    'Draft'
  )
}

export function generateBirthCertificatePDF(data: BirthCertificateFormData) {
  buildBirthCertificatePDFDoc(data).save(
    `Birth_Certificate_${nicFileId(data)}.pdf`,
  )
}

export function printBirthCertificatePDF(data: BirthCertificateFormData) {
  printPdfDoc(buildBirthCertificatePDFDoc(data))
}

export function generateDrivingLicensePDF(data: DrivingLicenseFormData) {
  buildDrivingLicensePDFDoc(data).save(
    `Driving_License_${nicFileId(data)}.pdf`,
  )
}

export function printDrivingLicensePDF(data: DrivingLicenseFormData) {
  printPdfDoc(buildDrivingLicensePDFDoc(data))
}

export function generatePoliceClearancePDF(data: PoliceClearanceFormData) {
  buildPoliceClearancePDFDoc(data).save(
    `Police_Clearance_${nicFileId(data)}.pdf`,
  )
}

export function printPoliceClearancePDF(data: PoliceClearanceFormData) {
  printPdfDoc(buildPoliceClearancePDFDoc(data))
}

export function generateNICRenewalPDF(data: NICRenewalFormData) {
  buildNICRenewalPDFDoc(data).save(`NIC_Renewal_${nicFileId(data)}.pdf`)
}

export function printNICRenewalPDF(data: NICRenewalFormData) {
  printPdfDoc(buildNICRenewalPDFDoc(data))
}
