import jsPDF from 'jspdf'
import type { PassportFormData } from '@/components/PassportForm'

export function generatePassportPDF(data: PassportFormData) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  })

  doc.setTextColor(0, 0, 0)

  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('SRI LANKA DEPARTMENT OF IMMIGRATION & EMIGRATION', 105, 20, {
    align: 'center',
  })

  doc.setFontSize(16)
  doc.text('PASSPORT APPLICATION (FORM K)', 105, 30, { align: 'center' })

  doc.setLineWidth(0.5)
  doc.line(20, 35, 190, 35)

  doc.setFontSize(11)
  let yPos = 50
  const lineSpacing = 12
  const pageWidth = doc.internal.pageSize.getWidth()
  const valueMaxWidth = pageWidth - 75

  const drawField = (label: string, value: string | undefined) => {
    doc.setFont('helvetica', 'bold')
    doc.text(`${label}:`, 20, yPos)

    doc.setFont('helvetica', 'normal')
    const display =
      value && value.length > 0 ? value : '________________________'

    const lines = doc.splitTextToSize(display, valueMaxWidth)
    doc.text(lines, 70, yPos)
    yPos += lineSpacing * Math.max(1, lines.length)
  }

  drawField('Surname', data.surname)
  drawField('Other Names', data.otherNames)
  drawField('NIC Number', data.nationalId)
  drawField('Date of Birth', data.dateOfBirth)
  drawField('Place of Birth', data.placeOfBirth)
  drawField('Gender', data.gender)

  yPos += 5
  drawField('Permanent Address', data.address)
  drawField('District', data.district)
  drawField('Phone Number', data.phone)
  drawField('Service Type', data.serviceType)

  yPos += 30
  doc.setLineWidth(0.2)
  doc.line(20, yPos, 80, yPos)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'italic')
  doc.text("Applicant's Signature", 30, yPos + 5)

  doc.text('Generated by Rathna AI Assistant', 105, 280, { align: 'center' })

  const fileId =
    data.nationalId?.replace(/[^\w]/g, '') ||
    data.surname?.replace(/\s+/g, '_') ||
    'Draft'
  doc.save(`Passport_Application_${fileId}.pdf`)
}
